name: Run Tests
on: 
  - pull_request
  - push
jobs:
  test:
    strategy:
      matrix:
        go-versions: [1.17.x, 1.19.x]
        test-os: [ubuntu-latest]
    runs-on: ${{ matrix.test-os }}
    steps:
      
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-versions }}

    - uses: actions/checkout@v3
      
    - name: Run Vet
      run: |
        go vet ./...

    - name: Run Lint
      run: |
        go get -v golang.org/x/lint/golint
        go install golang.org/x/lint/golint
        golint .

    - name: Run Tests
      run: |
        go test -v ./...
        go test -v -race ./...